### PR TITLE
Create Rifampin_rgt_fasta

### PR DESCRIPTION
**Pull request by vvons**

### CODE REVIEW

**Comment by vvons** [comment]
Yea, that’s the way to do it?

VV

**Comment by olsonanl** [comment]
Yup, worked great. I did rename it to end in .fasta.txt to match the rest.

On Mar 12, 2019, at 11:28 AM, vvons <notifications@github.com<mailto:notifications@github.com>> wrote:

Yea, that’s the way to do it?

VV

**Comment by vvons** [comment]
Will do the right ending myself with the next file. 
Have you started the recompute?

VV

**Comment by olsonanl** [comment]
not yet

On Mar 12, 2019, at 11:41 AM, vvons <notifications@github.com<mailto:notifications@github.com>> wrote:

Will do the right ending myself with the next file.
Have you started the recompute?

VV

**Pull request merged**
